Migrate Useful `webpa-common/logging` Utilities & Remove `go-kit/kit/log`, `go-kit/log`
xmidt-org/sallust pull request #39
Opened 2022-10-19 16:59 UTC by denopink

What's included:
- #38 
- #37 
- #36 

closes #38 #37 #36

2022-10-19 19:50 UTC, renaz6 approved these changes
Don't forget to update the Changelog with your work!

Otherwise, lgtm!

2022-10-26 16:23 UTC, johnabass requested changes

2022-10-26 16:23 UTC, johnabass commented on enrich.go
> +type Contextual interface {
This is one of the concepts we want to drop.  We don't want to carry this over into `sallust`.  Any functionality that relies on this should be either deleted or refactored.

The problem with this approach is that it's ambiguous:  does it flatten the fields or indicate a new object marshaled into JSON?  This wasn't a problem with `go-kit`, but it is with `zap`.

2022-11-02 19:05 UTC, johnabass approved these changes
👍

2022-11-03 15:49 UTC, merged